import 'package:flutter/material.dart';

/* UndefinedNode ACCORDIAN
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedACCORDIANWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
