import 'package:flutter/material.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedtherapistwidget2/generated/GeneratedLogowhiteWidget2.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedtherapistwidget2/generated/GeneratedBackArrowWidget2.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedtherapistwidget2/generated/GeneratedPurpleupperbgWidget4.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedtherapistwidget2/generated/GeneratedFrame4Widget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedtherapistwidget2/generated/GeneratedIconbarWidget.dart';

/* Frame Therapist
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTherapistWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 641.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 225, 203, 234),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 87.0,
                child: GeneratedPurpleupperbgWidget4(),
              ),
              Positioned(
                left: 24.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 86.0,
                child: GeneratedLogowhiteWidget2(),
              ),
              Positioned(
                left: 1.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 472.0,
                child: GeneratedFrame4Widget(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: null,
                bottom: 0.0,
                width: 360.0,
                height: 70.0,
                child: GeneratedIconbarWidget(),
              ),
              // Positioned(
              //   left: 293.0,
              //   top: 27.0,
              //   right: null,
              //   bottom: null,
              //   width: 32.0,
              //   height: 32.0,
              //   child: GeneratedBackArrowWidget2(),
              // )
            ]),
      ),
    ));
  }
}
