import 'package:flutter/material.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent2widget/generated/GeneratedGroup46Widget1.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent2widget/generated/GeneratedLogowhiteWidget11.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent2widget/generated/GeneratedGalleryWidget1.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent2widget/generated/GeneratedForwardButtonWidget1.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent2widget/generated/GeneratedRectangle8Widget5.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent2widget/generated/GeneratedGroup47Widget1.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent2widget/generated/GeneratedGroup6Widget6.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent2widget/generated/GeneratedGroup3Widget2.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent2widget/generated/GeneratedRectangle11Widget2.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent2widget/generated/GeneratedPurpleupperbgWidget15.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent2widget/generated/GeneratedRectangle13Widget7.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent2widget/generated/GeneratedNewVentWidget1.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent2widget/generated/GeneratedRectangle9Widget2.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent2widget/generated/GeneratedRectangle12Widget7.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent2widget/generated/GeneratedRectangle10Widget2.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent2widget/generated/GeneratedBackArrowWidget10.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent2widget/generated/GeneratedPurpleupperbgWidget14.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent2widget/generated/GeneratedRectangle7Widget9.dart';

/* Frame new vent 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNewvent2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 2.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 105.0,
                child: GeneratedPurpleupperbgWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: 353.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 244.0,
                child: GeneratedPurpleupperbgWidget15(),
              ),
              Positioned(
                left: 24.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 86.0,
                child: GeneratedLogowhiteWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedGroup6Widget6(),
              ),
              Positioned(
                left: 36.0,
                top: 119.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 26.0,
                child: GeneratedNewVentWidget1(),
              ),
              Positioned(
                left: 37.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 145.0,
                child: GeneratedGroup3Widget2(),
              ),
              Positioned(
                left: 242.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedGroup46Widget1(),
              ),
              Positioned(
                left: 289.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedGroup47Widget1(),
              ),
              Positioned(
                left: 43.0,
                top: 363.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 23.0,
                child: GeneratedGalleryWidget1(),
              ),
              Positioned(
                left: 40.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 48.0,
                child: GeneratedRectangle7Widget9(),
              ),
              Positioned(
                left: 132.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 48.0,
                child: GeneratedRectangle8Widget5(),
              ),
              Positioned(
                left: 226.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 48.0,
                child: GeneratedRectangle9Widget2(),
              ),
              Positioned(
                left: 226.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 48.0,
                child: GeneratedRectangle10Widget2(),
              ),
              Positioned(
                left: 132.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 48.0,
                child: GeneratedRectangle11Widget2(),
              ),
              Positioned(
                left: 40.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 48.0,
                child: GeneratedRectangle12Widget7(),
              ),
              Positioned(
                left: 293.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedBackArrowWidget10(),
              ),
              Positioned(
                left: 293.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedForwardButtonWidget1(),
              ),
              Positioned(
                left: 87.0,
                top: 191.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 114.0,
                child: GeneratedRectangle13Widget7(),
              )
            ]),
      ),
    ));
  }
}
