import 'package:flutter/material.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedsignupwidget/generated/GeneratedOrWidget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedsignupwidget/generated/GeneratedAlreadyhaveanaccountLOGINWidget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedsignupwidget/generated/GeneratedPurpleupperbgWidget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedsignupwidget/generated/GeneratedGETSTARTEDBUTTONWidget1.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedsignupwidget/generated/GeneratedTYPEBOXWidget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedsignupwidget/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedsignupwidget/generated/GeneratedWHITEBELOWBGWidget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedsignupwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedsignupwidget/generated/GeneratedPasswordWidget.dart';

import '../generatedtherapistwidget2/generated/GeneratedLogowhiteWidget2.dart';

/* Frame sign up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 225, 203, 234),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 157.0,
                child: GeneratedPurpleupperbgWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 38.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 150.0,
                child: GeneratedLogowhiteWidget2(),
              ),
              // Positioned(
              //   left: 40.0,
              //   top: 94.0,
              //   right: null,
              //   bottom: null,
              //   width: 225.0,
              //   height: 53.0,
              //   child: GeneratedSignUpWidget(),
              // ),
              Positioned(
                left: 51.0,
                top: 203.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 29.0,
                child: GeneratedEmailWidget(),
              ),
              Positioned(
                left: 51.0,
                top: 235.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 126.0,
                child: GeneratedTYPEBOXWidget(),
              ),
              Positioned(
                left: 51.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 29.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 170.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 29.0,
                child: GeneratedOrWidget(),
              ),
              Positioned(
                left: 113.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 42.0,
                child: GeneratedGETSTARTEDBUTTONWidget1(),
              ),
              Positioned(
                left: 116.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 40.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedWHITEBELOWBGWidget(),
              ),
              Positioned(
                left: 84.0,
                top: 599.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 17.0,
                child: GeneratedAlreadyhaveanaccountLOGINWidget(),
              )
            ]),
      ),
    ));
  }
}
