import 'package:flutter/material.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframe4widget/generated/GeneratedGroup5Widget2.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframe4widget/generated/GeneratedRectangle10Widget4.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframe4widget/generated/GeneratedRectangle13Widget10.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframe4widget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframe4widget/generated/GeneratedGroup5Widget3.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframe4widget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframe4widget/generated/GeneratedRectangle16Widget1.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframe4widget/generated/GeneratedRectangle12Widget8.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframe4widget/generated/GeneratedRectangle14Widget.dart';

/* Frame wireframe 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWireframe4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 76.0,
                child: GeneratedGroup5Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 76.0,
                child: GeneratedGroup5Widget3(),
              ),
              Positioned(
                left: 16.0,
                top: 122.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 60.0,
                child: GeneratedRectangle10Widget4(),
              ),
              Positioned(
                left: 48.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 357.0,
                child: GeneratedRectangle12Widget8(),
              ),
              Positioned(
                left: 69.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 50.0,
                child: GeneratedRectangle13Widget10(),
              ),
              Positioned(
                left: 69.0,
                top: 295.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 50.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 69.0,
                top: 362.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 50.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 69.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 50.0,
                child: GeneratedRectangle16Widget1(),
              ),
              Positioned(
                left: 69.0,
                top: 497.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 50.0,
                child: GeneratedRectangle17Widget(),
              )
            ]),
      ),
    ));
  }
}
