description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies:
  badges: ^2.0.3
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  path_drawing: ^1.0.0
  video_player: ^2.4.10
  video_player_web_hls: ^1.0.0+1
dev_dependencies:
  flutter_test:
    sdk: "flutter"
environment:
  sdk: ">=2.12.0 <3.0.0"
flutter:
  assets:
    - "assets/images/"
    - "assets/videos/StepTouch.mp4"
  fonts:
    - family: "Inter"
      fonts:
        - asset: "fonts/Inter-regular.ttf"
          style: "normal"
          weight: 400
        - asset: "fonts/Inter-700.ttf"
          style: "normal"
          weight: 700
        - asset: "fonts/Inter-500.ttf"
          style: "normal"
          weight: 500
    - family: "Archivo Black"
      fonts:
        - asset: "fonts/ArchivoBlack-regular.ttf"
          style: "normal"
          weight: 400
  uses-material-design: true
