import 'package:flutter/material.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedgetstartedwidget/generated/GeneratedLogodarkpurpleWidget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedgetstartedwidget/generated/GeneratedCanweskiptothegoodpartWidget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedgetstartedwidget/generated/GeneratedDarkbgWidget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedgetstartedwidget/generated/GeneratedWhitebgWidget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedgetstartedwidget/generated/GeneratedGETSTARTEDBUTTONWidget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedgetstartedwidget/generated/GeneratedHeartgirlWidget.dart';

/* Frame get started
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGetstartedWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 225, 203, 234),
                ),
              ),
              Positioned(
                left: 40.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 281.0,
                height: 199.0,
                child: GeneratedHeartgirlWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 282.0,
                child: GeneratedDarkbgWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 251.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 309.0,
                child: GeneratedWhitebgWidget(),
              ),
              Positioned(
                left: 62.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 237.0,
                height: 133.0,
                child: GeneratedLogodarkpurpleWidget(),
              ),
              Positioned(
                left: 94.0,
                top: 381.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 17.0,
                child: GeneratedCanweskiptothegoodpartWidget(),
              ),
              Positioned(
                left: 112.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 42.0,
                child: GeneratedGETSTARTEDBUTTONWidget(),
              )
            ]),
      ),
    ));
  }
}
