import 'package:flutter/material.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedplayerwidget/generated/GeneratedBackArrowWidget8.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedplayerwidget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedplayerwidget/generated/GeneratedPurpleupperbgWidget11.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedplayerwidget/generated/GeneratedGroup6Widget4.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedplayerwidget/generated/GeneratedMaskgroupWidget6.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedplayerwidget/generated/GeneratedWITHYOUWidget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedplayerwidget/generated/GeneratedRewindWidget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedplayerwidget/generated/GeneratedPauseButtonWidget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedplayerwidget/generated/GeneratedCALMWidget2.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedplayerwidget/generated/GeneratedLogowhiteWidget9.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedplayerwidget/generated/GeneratedFastForwardWidget.dart';

/* Frame player
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPlayerWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 2.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 157.0,
                child: GeneratedPurpleupperbgWidget11(),
              ),
              Positioned(
                left: 24.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 86.0,
                child: GeneratedLogowhiteWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedGroup6Widget4(),
              ),
              Positioned(
                left: 75.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 210.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 149.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 17.0,
                child: GeneratedWITHYOUWidget(),
              ),
              Positioned(
                left: 151.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 29.0,
                child: GeneratedCALMWidget2(),
              ),
              Positioned(
                left: 235.0,
                top: 473.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedFastForwardWidget(),
              ),
              Positioned(
                left: 84.0,
                top: 473.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedRewindWidget(),
              ),
              Positioned(
                left: 88.0,
                top: 148.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 184.0,
                child: GeneratedMaskgroupWidget6(),
              ),
              Positioned(
                left: 160.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedPauseButtonWidget(),
              ),
              Positioned(
                left: 293.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedBackArrowWidget8(),
              )
            ]),
      ),
    ));
  }
}
