import 'package:flutter/material.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframewidget/generated/GeneratedGroup2Widget6.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframewidget/generated/GeneratedRectangle5Widget2.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframewidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframewidget/generated/GeneratedRectangle6Widget15.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframewidget/generated/GeneratedGroup1Widget2.dart';

/* Frame wireframe
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWireframeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 60.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 76.0,
                child: GeneratedGroup1Widget2(),
              ),
              Positioned(
                left: 41.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 292.0,
                height: 184.0,
                child: GeneratedRectangle5Widget2(),
              ),
              Positioned(
                left: 36.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 292.0,
                height: 184.0,
                child: GeneratedRectangle6Widget15(),
              ),
              Positioned(
                left: 0.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 76.0,
                child: GeneratedGroup2Widget6(),
              )
            ]),
      ),
    ));
  }
}
