import 'package:flutter/material.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewventwidget/generated/GeneratedGroup47Widget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewventwidget/generated/GeneratedNewVentWidget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewventwidget/generated/GeneratedRectangle11Widget1.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewventwidget/generated/GeneratedBackArrowWidget9.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewventwidget/generated/GeneratedGroup3Widget1.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewventwidget/generated/GeneratedPurpleupperbgWidget12.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewventwidget/generated/GeneratedPurpleupperbgWidget13.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewventwidget/generated/GeneratedLogowhiteWidget10.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewventwidget/generated/GeneratedRectangle9Widget1.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewventwidget/generated/GeneratedRectangle10Widget1.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewventwidget/generated/GeneratedGalleryWidget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewventwidget/generated/GeneratedRectangle8Widget3.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewventwidget/generated/GeneratedGroup6Widget5.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewventwidget/generated/GeneratedRectangle7Widget8.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewventwidget/generated/GeneratedRectangle12Widget6.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewventwidget/generated/GeneratedGroup46Widget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewventwidget/generated/GeneratedForwardButtonWidget.dart';

/* Frame new vent
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNewventWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 2.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 105.0,
                child: GeneratedPurpleupperbgWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: 353.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 244.0,
                child: GeneratedPurpleupperbgWidget13(),
              ),
              Positioned(
                left: 24.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 86.0,
                child: GeneratedLogowhiteWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedGroup6Widget5(),
              ),
              Positioned(
                left: 36.0,
                top: 119.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 26.0,
                child: GeneratedNewVentWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 145.0,
                child: GeneratedGroup3Widget1(),
              ),
              Positioned(
                left: 242.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedGroup46Widget(),
              ),
              Positioned(
                left: 289.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedGroup47Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 363.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 23.0,
                child: GeneratedGalleryWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 48.0,
                child: GeneratedRectangle7Widget8(),
              ),
              Positioned(
                left: 132.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 48.0,
                child: GeneratedRectangle8Widget3(),
              ),
              Positioned(
                left: 226.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 48.0,
                child: GeneratedRectangle9Widget1(),
              ),
              Positioned(
                left: 226.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 48.0,
                child: GeneratedRectangle10Widget1(),
              ),
              Positioned(
                left: 132.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 48.0,
                child: GeneratedRectangle11Widget1(),
              ),
              Positioned(
                left: 40.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 48.0,
                child: GeneratedRectangle12Widget6(),
              ),
              Positioned(
                left: 293.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedBackArrowWidget9(),
              ),
              Positioned(
                left: 293.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedForwardButtonWidget(),
              )
            ]),
      ),
    ));
  }
}
