import 'package:flutter/material.dart';

/* UndefinedNode side bar navigation
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSidebarnavigationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
