import 'package:flutter/material.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframe2widget/generated/GeneratedRectangle7Widget11.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframe2widget/generated/GeneratedGroup3Widget5.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframe2widget/generated/GeneratedRectangle9Widget3.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframe2widget/generated/GeneratedGroup3Widget4.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframe2widget/generated/GeneratedRectangle7Widget12.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframe2widget/generated/GeneratedRectangle8Widget7.dart';

/* Frame wireframe 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWireframe2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 76.0,
                child: GeneratedGroup3Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 76.0,
                child: GeneratedGroup3Widget5(),
              ),
              Positioned(
                left: 16.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 60.0,
                child: GeneratedRectangle7Widget11(),
              ),
              Positioned(
                left: 16.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 104.0,
                child: GeneratedRectangle7Widget12(),
              ),
              Positioned(
                left: 207.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 152.0,
                child: GeneratedRectangle8Widget7(),
              ),
              Positioned(
                left: 21.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 159.0,
                height: 228.0,
                child: GeneratedRectangle9Widget3(),
              )
            ]),
      ),
    ));
  }
}
