import 'package:flutter/material.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedventingwidget/generated/GeneratedVentingWidget1.dart';

/* Frame venting
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVentingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 639.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 1068.0,
                child: GeneratedVentingWidget1(),
              )
            ]),
      ),
    ));
  }
}
