import 'package:flutter/material.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedtherapistinfo3widget/generated/GeneratedPurpleupperbgWidget7.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedtherapistinfo3widget/generated/GeneratedFrame7Widget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedtherapistinfo3widget/generated/GeneratedIconbarWidget3.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedtherapistinfo3widget/generated/GeneratedLogowhiteWidget5.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedtherapistinfo3widget/generated/GeneratedBackArrowWidget5.dart';

/* Frame Therapist info 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTherapistinfo3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 641.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 87.0,
                child: GeneratedPurpleupperbgWidget7(),
              ),
              Positioned(
                left: 24.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 86.0,
                child: GeneratedLogowhiteWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 480.0,
                child: GeneratedFrame7Widget(),
              ),
              Positioned(
                left: 293.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedBackArrowWidget5(),
              ),
              Positioned(
                left: 1.0,
                top: null,
                right: null,
                bottom: 0.0,
                width: 360.0,
                height: 70.0,
                child: GeneratedIconbarWidget3(),
              )
            ]),
      ),
    ));
  }
}
