import 'package:flutter/material.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedalbumwidget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedalbumwidget/generated/GeneratedCALMWidget1.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedalbumwidget/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedalbumwidget/generated/GeneratedPurpleupperbgWidget10.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedalbumwidget/generated/GeneratedLogowhiteWidget8.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedalbumwidget/generated/GeneratedGroup6Widget3.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedalbumwidget/generated/GeneratedGroup14Widget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedalbumwidget/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedalbumwidget/generated/GeneratedBackArrowWidget7.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedalbumwidget/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedalbumwidget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedalbumwidget/generated/GeneratedGroup13Widget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedalbumwidget/generated/GeneratedGroup12Widget.dart';

/* Frame album
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAlbumWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 225, 203, 234),
                ),
              ),
              Positioned(
                left: 2.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 87.0,
                child: GeneratedPurpleupperbgWidget10(),
              ),
              Positioned(
                left: 24.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 86.0,
                child: GeneratedLogowhiteWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedGroup6Widget3(),
              ),
              Positioned(
                left: 120.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 47.0,
                child: GeneratedCALMWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 364.0,
                child: GeneratedGroup7Widget(),
              ),
              Positioned(
                left: 62.0,
                top: 213.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 32.0,
                child: GeneratedGroup8Widget(),
              ),
              Positioned(
                left: 62.0,
                top: 261.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 32.0,
                child: GeneratedGroup9Widget(),
              ),
              Positioned(
                left: 62.0,
                top: 309.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 32.0,
                child: GeneratedGroup10Widget(),
              ),
              Positioned(
                left: 62.0,
                top: 357.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 32.0,
                child: GeneratedGroup11Widget(),
              ),
              Positioned(
                left: 62.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 32.0,
                child: GeneratedGroup12Widget(),
              ),
              Positioned(
                left: 62.0,
                top: 453.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 32.0,
                child: GeneratedGroup13Widget(),
              ),
              Positioned(
                left: 59.0,
                top: 501.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 32.0,
                child: GeneratedGroup14Widget(),
              ),
              Positioned(
                left: 293.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedBackArrowWidget7(),
              )
            ]),
      ),
    ));
  }
}
