import 'package:flutter/material.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframe3widget/generated/GeneratedRectangle7Widget13.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframe3widget/generated/GeneratedGroup4Widget1.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframe3widget/generated/GeneratedGroup4Widget2.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframe3widget/generated/GeneratedRectangle11Widget3.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedwireframe3widget/generated/GeneratedRectangle10Widget3.dart';

/* Frame wireframe 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWireframe3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 76.0,
                child: GeneratedGroup4Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 76.0,
                child: GeneratedGroup4Widget2(),
              ),
              Positioned(
                left: 34.0,
                top: 198.0,
                right: null,
                bottom: null,
                width: 292.0,
                height: 226.0,
                child: GeneratedRectangle7Widget13(),
              ),
              Positioned(
                left: 93.0,
                top: 107.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 60.0,
                child: GeneratedRectangle10Widget3(),
              ),
              Positioned(
                left: 36.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 278.0,
                height: 119.0,
                child: GeneratedRectangle11Widget3(),
              )
            ]),
      ),
    ));
  }
}
