import 'package:flutter/material.dart';

/* UndefinedNode edit profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEditprofileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
