import 'package:flutter/material.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent4widget/generated/GeneratedGETSTARTEDBUTTONWidget5.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent4widget/generated/GeneratedRectangle13Widget9.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent4widget/generated/GeneratedNewVentWidget3.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent4widget/generated/GeneratedGroup2Widget5.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent4widget/generated/GeneratedPurpleupperbgWidget17.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent4widget/generated/GeneratedGroup6Widget8.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent4widget/generated/GeneratedBackArrowWidget12.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent4widget/generated/GeneratedLogowhiteWidget13.dart';

/* Frame new vent 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNewvent4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 2.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 105.0,
                child: GeneratedPurpleupperbgWidget17(),
              ),
              Positioned(
                left: 24.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 86.0,
                child: GeneratedLogowhiteWidget13(),
              ),
              Positioned(
                left: 0.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedGroup6Widget8(),
              ),
              Positioned(
                left: 36.0,
                top: 119.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 26.0,
                child: GeneratedNewVentWidget3(),
              ),
              Positioned(
                left: 293.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedBackArrowWidget12(),
              ),
              Positioned(
                left: 35.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 219.0,
                child: GeneratedGroup2Widget5(),
              ),
              Positioned(
                left: 70.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 218.0,
                height: 131.0,
                child: GeneratedRectangle13Widget9(),
              ),
              Positioned(
                left: 112.0,
                top: 426.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 42.0,
                child: GeneratedGETSTARTEDBUTTONWidget5(),
              )
            ]),
      ),
    ));
  }
}
