import 'package:flutter/material.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedbraingymwidget/generated/GeneratedRectangle7Widget1.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedloginwidget/generated/GeneratedGETSTARTEDBUTTONWidget2.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedloginwidget/generated/GeneratedOrWidget1.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedloginwidget/generated/GeneratedGroup1Widget1.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedloginwidget/generated/GeneratedPasswordWidget1.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedloginwidget/generated/GeneratedDonthaveanaccountSIGNUPWidget.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedloginwidget/generated/GeneratedEmailWidget1.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedloginwidget/generated/GeneratedWHITEBELOWBGWidget1.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedloginwidget/generated/GeneratedTYPEBOXWidget1.dart';
import 'package:flutterapp/ye_20zindagiapp/generatedloginwidget/generated/GeneratedPurpleupperbgWidget1.dart';

import '../generatedbraingymwidget/generated/GeneratedRectangle6Widget1.dart';

/* Frame log in
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 225, 203, 234),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 157.0,
                child: GeneratedPurpleupperbgWidget1(),
              ),
              Positioned(
                left: 40.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 225.0,
                height: 53.0,
                child: Container(
                  width: 290.0,
                  height: 219.0,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(0.0),
                  ),
                  child: Stack(
                      fit: StackFit.expand,
                      alignment: Alignment.center,
                      clipBehavior: Clip.none,
                      children: [
                        Positioned(
                          left: 0.0,
                          top: 0.0,
                          right: null,
                          bottom: null,
                          width: 290.0,
                          height: 219.0,
                          child: GeneratedRectangle6Widget1(),
                        ),
                        Positioned(
                          left: 16.0,
                          top: 16.0,
                          right: null,
                          bottom: null,
                          width: 259.0,
                          height: 187.0,
                          child: GeneratedRectangle7Widget1(),
                        )
                      ]),
                ),
              ),
              Positioned(
                left: 51.0,
                top: 203.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 29.0,
                child: GeneratedEmailWidget1(),
              ),
              Positioned(
                left: 51.0,
                top: 235.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 126.0,
                child: GeneratedTYPEBOXWidget1(),
              ),
              Positioned(
                left: 51.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 29.0,
                child: GeneratedPasswordWidget1(),
              ),
              Positioned(
                left: 170.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 29.0,
                child: GeneratedOrWidget1(),
              ),
              Positioned(
                left: 113.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 42.0,
                child: GeneratedGETSTARTEDBUTTONWidget2(),
              ),
              Positioned(
                left: 116.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 40.0,
                child: GeneratedGroup1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedWHITEBELOWBGWidget1(),
              ),
              Positioned(
                left: 86.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 17.0,
                child: GeneratedDonthaveanaccountSIGNUPWidget(),
              )
            ]),
      ),
    ));
  }
}
