import 'package:flutter/material.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent3widget/generated/GeneratedGETSTARTEDBUTTONWidget4.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent3widget/generated/GeneratedGETSTARTEDBUTTONWidget3.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent3widget/generated/GeneratedNewVentWidget2.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent3widget/generated/GeneratedGroup6Widget7.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent3widget/generated/GeneratedBackArrowWidget11.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent3widget/generated/GeneratedGroup2Widget4.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent3widget/generated/GeneratedPurpleupperbgWidget16.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent3widget/generated/GeneratedRectangle13Widget8.dart';
import 'package:flutterapp/ye_20zindagiapp/generatednewvent3widget/generated/GeneratedLogowhiteWidget12.dart';

/* Frame new vent 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNewvent3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 2.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 105.0,
                child: GeneratedPurpleupperbgWidget16(),
              ),
              Positioned(
                left: 24.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 86.0,
                child: GeneratedLogowhiteWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedGroup6Widget7(),
              ),
              Positioned(
                left: 36.0,
                top: 119.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 26.0,
                child: GeneratedNewVentWidget2(),
              ),
              Positioned(
                left: 293.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedBackArrowWidget11(),
              ),
              Positioned(
                left: 35.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 219.0,
                child: GeneratedGroup2Widget4(),
              ),
              Positioned(
                left: 70.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 218.0,
                height: 131.0,
                child: GeneratedRectangle13Widget8(),
              ),
              Positioned(
                left: 112.0,
                top: 426.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 42.0,
                child: GeneratedGETSTARTEDBUTTONWidget3(),
              ),
              Positioned(
                left: 112.0,
                top: 482.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 42.0,
                child: GeneratedGETSTARTEDBUTTONWidget4(),
              )
            ]),
      ),
    ));
  }
}
